GET http://localhost:5007/places

###

GET http://localhost:5007/place/1

###
POST http://localhost:5007/place
Content-Type: application/json

{
    "name": "destinasi"
}

###
POST http://localhost:5007/place
Content-Type: application/json

{
    "name": "restoran"
}


###
GET http://localhost:5007/tomohonlokas